name: driver-independent-ci
on:
  pull_request:
    branches: [main]
jobs:
  driver-independent-ci:
    name: driver-independent-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo plan5 fail; exit 1
